# Generated by Django 5.1.3 on 2025-06-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_profile_bio_remove_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
